# Generated by Django 3.2.9 on 2022-01-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('talle', models.IntegerField()),
                ('hayStock', models.BooleanField()),
            ],
        ),
    ]
