# Generated by Django 3.2.9 on 2022-01-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0003_auto_20220109_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('talle', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Botines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('talle', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pantalones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('talle', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Remeras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('talle', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZapatillasDeportivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('talle', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
