# Generated by Django 3.2.9 on 2022-01-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0004_accesorios_botines_pantalones_remeras_zapatillasdeportivas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
    ]
