# Generated by Django 3.2.9 on 2022-01-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appfinal', '0005_probando'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Probando',
        ),
    ]
